# Numpy

### Numpy:"num"means numbers and "py" means python

### import numpy as np

In [4]:
import numpy as np

In [6]:
simple_list=[4,5,6]
np.array(simple_list)

array([4, 5, 6])

In [7]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [10]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(1,30,5)

array([ 1,  6, 11, 16, 21, 26])

In [14]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [27]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [28]:
np.random.rand(3,5)

array([[0.78825362, 0.06857093, 0.8923847 , 0.99123794, 0.58611089],
       [0.71300492, 0.24705464, 0.4541518 , 0.20126837, 0.85879391],
       [0.77510192, 0.63963146, 0.65777287, 0.11969817, 0.08454374]])

In [30]:
np.random.randint(1,100)

42

In [31]:
np.random.randint(20,50,100)

array([38, 32, 39, 21, 33, 27, 32, 31, 20, 48, 43, 39, 38, 46, 35, 35, 33,
       45, 36, 47, 33, 44, 24, 48, 30, 43, 22, 47, 24, 38, 46, 40, 46, 37,
       41, 48, 40, 23, 39, 38, 48, 31, 21, 37, 37, 24, 21, 20, 31, 26, 38,
       32, 31, 49, 33, 21, 22, 20, 20, 26, 33, 47, 27, 38, 23, 41, 28, 26,
       41, 27, 47, 44, 36, 43, 23, 24, 24, 47, 30, 30, 27, 48, 39, 25, 47,
       21, 42, 39, 20, 48, 28, 20, 40, 35, 23, 38, 20, 45, 33, 35])

In [41]:
simple_array=np.arange(30)
simple_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [46]:
rand_array=np.random.randint(0,10,50)
rand_array

array([3, 8, 0, 5, 6, 3, 5, 1, 4, 9, 5, 6, 2, 5, 3, 0, 5, 3, 6, 8, 8, 3,
       2, 7, 3, 9, 7, 7, 6, 0, 6, 0, 9, 0, 3, 9, 1, 3, 5, 3, 9, 7, 2, 6,
       1, 0, 9, 5, 8, 9])

In [47]:
rand_array.max()

9

In [48]:
rand_array.min()

0

In [49]:
rand_array.argmax()

9

In [52]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
a=np.random.rand(2,3)
a

array([[0.49852148, 0.99710904, 0.84732293],
       [0.75563717, 0.80754779, 0.37809834]])

In [56]:
a.T

array([[0.49852148, 0.75563717],
       [0.99710904, 0.80754779],
       [0.84732293, 0.37809834]])

In [57]:
sample_array=np.arange(1,10)
sample_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
sample_array[1]

2

In [60]:
sample_array[2:5]

array([3, 4, 5])

In [62]:
sample_array[1:4]=100
sample_array

array([  1, 100, 100, 100,   5,   6,   7,   8,   9])

In [63]:
sample_array[:]=1000
sample_array

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

### Numpy->play with arrays(numbers)
### pandas->dataset
### matplotlib->data visualization
### seaborn->data visualization
### scipy->statistical
### sklearn->aldorithm